// ============================================================
// SPANISH RACING SERIES — DATA T38
// ============================================================

const SRS = {
  season: { number: 38, title: "Temporada 38" },

  // ── PILOTOS ────────
  pilotos: [
    {
      pos: 1,
      nombre: "Romus Toras",
      equipo: "50 Rizia Royal Racing",
      puntos: 809,
      clasificado: false,
    },
    {
      pos: 2,
      nombre: "Leoo Ferreira",
      equipo: "07 CRT Competition",
      puntos: 771,
      clasificado: false,
    },
    {
      pos: 3,
      nombre: "André Prov",
      equipo: "Tortuga",
      puntos: 728,
      clasificado: false,
    },
    {
      pos: 4,
      nombre: "Valdi CT",
      equipo: "77 Campos Racing F1",
      puntos: 629,
      clasificado: false,
    },
    {
      pos: 5,
      nombre: "Vasvo Lao",
      equipo: "Subaru F1 Team",
      puntos: 595,
      clasificado: false,
    },
    {
      pos: 6,
      nombre: "Thiago Campos",
      equipo: "Mercedes",
      puntos: 564,
      clasificado: false,
    },
    {
      pos: 7,
      nombre: "Eduardo Calvo",
      equipo: "72 CTC VCR Foxtrot",
      puntos: 421,
      clasificado: false,
    },
    {
      pos: 8,
      nombre: "Sergio Solano",
      equipo: "13 CRT Competition",
      puntos: 393,
      clasificado: false,
    },
    {
      pos: 9,
      nombre: "Giacomina Leclerc",
      equipo: "Patria Italia",
      puntos: 369,
      clasificado: false,
    },
    {
      pos: 10,
      nombre: "Alexis Iceman",
      equipo: "00 CRT Competition",
      puntos: 341,
      clasificado: false,
    },
    {
      pos: 11,
      nombre: "Cristian Ezpeleta",
      equipo: "99 Campos Racing F1",
      puntos: 278,
      clasificado: false,
    },
    {
      pos: 12,
      nombre: "Pablo Mafias",
      equipo: "Aston Martin F1 Team Mafias",
      puntos: 274,
      clasificado: false,
    },
    {
      pos: 13,
      nombre: "Juan Garcia",
      equipo: "Ferrari F1 Team",
      puntos: 222,
      clasificado: false,
    },
    {
      pos: 14,
      nombre: "Antonio Pinillos",
      equipo: "Red Bull Pinkustercia F1 Team",
      puntos: 112,
      clasificado: false,
    },
    {
      pos: 15,
      nombre: "Álvaro Redondo",
      equipo: "36 CTC VCR FTSE",
      puntos: 111,
      clasificado: false,
    },
    {
      pos: 16,
      nombre: "Julio Maidana",
      equipo: "18 BMW team",
      puntos: 107,
      clasificado: false,
    },
    {
      pos: 17,
      nombre: "Freya Anafi",
      equipo: "Renfe Cercanías RT",
      puntos: 105,
      clasificado: false,
    },
    {
      pos: 18,
      nombre: "Christian Horny",
      equipo: "15 Zeta Racing",
      puntos: 79,
      clasificado: false,
    },
    {
      pos: 19,
      nombre: "Alejandro Alonso",
      equipo: "3 Zetta Racing",
      puntos: 53,
      clasificado: false,
    },
    {
      pos: 20,
      nombre: "Mauro Reyes Hernández",
      equipo: "26 Zetta Racing",
      puntos: 40,
      clasificado: false,
    },
    {
      pos: 21,
      nombre: "Marc cr Rayo",
      equipo: "Rayito Team",
      puntos: 38,
      clasificado: false,
    },
    {
      pos: 22,
      nombre: "Templario VCR",
      equipo: "Hispania Racing Team",
      puntos: 35,
      clasificado: false,
    },
    {
      pos: 23,
      nombre: "Francisco Martínez",
      equipo: "Renfe Cercanías RT",
      puntos: 13,
      clasificado: false,
    },
    {
      pos: 24,
      nombre: "Lara Williams",
      equipo: "Williams Dacia",
      puntos: 11,
      clasificado: false,
    },
    {
      pos: 25,
      nombre: "Cristóbal Farías Galleguillos",
      equipo: "18 Zetta Racing",
      puntos: 9,
      clasificado: false,
    },
    {
      pos: 26,
      nombre: "Rui Acacio",
      equipo: "Flamengüam",
      puntos: 9,
      clasificado: false,
    },
    {
      pos: 27,
      nombre: "José Ortiz",
      equipo: "GoldBlue Bull RT",
      puntos: 7,
      clasificado: false,
    },
    {
      pos: 28,
      nombre: "Bongain François",
      equipo: "Porsche Racing",
      puntos: 6,
      clasificado: false,
    },
    {
      pos: 29,
      nombre: "Álvaro Molinelli",
      equipo: "Independent",
      puntos: 0,
      clasificado: false,
    },
    {
      pos: 30,
      nombre: "Andres Greniuk",
      equipo: "Independent",
      puntos: 0,
      clasificado: false,
    },
    {
      pos: 31,
      nombre: "Luis Reynoso",
      equipo: "Independent",
      puntos: 0,
      clasificado: false,
    },
    {
      pos: 32,
      nombre: "Leandro Fernández",
      equipo: "Independent",
      puntos: 0,
      clasificado: false,
    },
  ],

  // ── PARTICIPANTES DE LA COPA (32 managers) ────────────────
  copa: {
    participantes: [
      { pos: 1, nombre: "Romus Toras" },
      { pos: 2, nombre: "Valdi CT" },
      { pos: 3, nombre: "Álvaro Molinelli" },
      { pos: 4, nombre: "André Prov" },
      { pos: 5, nombre: "Giacomina Leclerc" },
      { pos: 6, nombre: "Andres Greniuk" },
      { pos: 7, nombre: "Sergio Solano" },
      { pos: 8, nombre: "Vasvo Lao" },
      { pos: 9, nombre: "Luis Reynoso" },
      { pos: 10, nombre: "Cristian Ezpeleta" },
      { pos: 11, nombre: "Leo Ferreira" },
      { pos: 12, nombre: "Javier Martín" },
      { pos: 13, nombre: "Thiago Campos" },
      { pos: 14, nombre: "Alexis Iceman" },
      { pos: 15, nombre: "Eduardo Calvo" },
      { pos: 16, nombre: "Bongain François" },
      { pos: 17, nombre: "Fran White Academy" },
      { pos: 18, nombre: "Freya Anafi" },
      { pos: 19, nombre: "José Ortiz" },
      { pos: 20, nombre: "Álvaro Redondo" },
      { pos: 21, nombre: "Marco Rodríguez" },
      { pos: 22, nombre: "Julio Maidana" },
      { pos: 23, nombre: "Cristóbal Farías Galleguillos" },
      { pos: 24, nombre: "Antonio Pinillos" },
      { pos: 25, nombre: "Alejandro Alonso" },
      { pos: 26, nombre: "Templario VCR" },
      { pos: 27, nombre: "Lara Williams" },
      { pos: 28, nombre: "Marc cr Rayo" },
      { pos: 29, nombre: "Rui Acacio" },
      { pos: 30, nombre: "Francisco Martínez" },
      { pos: 31, nombre: "Christian Horny" },
      { pos: 32, nombre: "Leandro Fernández" },
    ],
  },

  // ── JORNADAS ──────────────────────────────────────────────
  // Estructura de cada enfrentamiento:
  //   equipoA:   nombre del equipo izquierda
  //   posA:      posición final del equipo A en esa carrera
  //   equipoB:   nombre del equipo derecha
  //   posB:      posición final del equipo B en esa carrera
  //   ganador:   'A' | 'B' | null (null = pendiente)
  //
  // resultados: array con la clasificación individual de la carrera
  //   (solo disponible a partir de J6)
  jornadas: [
    // ── JORNADA 1 · Abu Dhabi ─────────────────────────────
    {
      numero: 1,
      circuito: "Abu Dhabi",
      completada: true,
      enfrentamientos: [
        {
          equipoA: "77 Campos Racing F1",
          posA: 1,
          equipoB: "43 Campos Racing F1",
          posB: 18,
          ganador: "A",
        },
        {
          equipoA: "07 CRT Competition",
          posA: 11,
          equipoB: "Ferrari",
          posB: 24,
          ganador: "A",
        },
        {
          equipoA: "18 Ferrari",
          posA: 20,
          equipoB: "00 CRT Competition",
          posB: 10,
          ganador: "B",
        },
        {
          equipoA: "Zetta",
          posA: 31,
          equipoB: "49 Honda Repsol",
          posB: 9,
          ganador: "B",
        },
        {
          equipoA: "Patria Italia",
          posA: 16,
          equipoB: "23 Foxtrot GP",
          posB: 5,
          ganador: "B",
        },
        {
          equipoA: "Subaru F1 Team",
          posA: 12,
          equipoB: "63 CRT Competition",
          posB: 2,
          ganador: "B",
        },
        {
          equipoA: "Tortuga",
          posA: 3,
          equipoB: "Red Bull Pinkustercia F1 Team",
          posB: 23,
          ganador: "A",
        },
        {
          equipoA: "18 Zetta Racing",
          posA: 19,
          equipoB: "99 Campos Racing F1",
          posB: 7,
          ganador: "B",
        },
        {
          equipoA: "Williams Racing",
          posA: 13,
          equipoB: "67 Renault Qatar Airways",
          posB: 30,
          ganador: "A",
        },
        {
          equipoA: "F. W. A.",
          posA: 22,
          equipoB: "3 Zetta Racing",
          posB: 15,
          ganador: "B",
        },
        {
          equipoA: "13 CRT Competition",
          posA: 4,
          equipoB: "50 Rizia Royal Racing",
          posB: 8,
          ganador: "A",
        },
        {
          equipoA: "Rayito Team",
          posA: 29,
          equipoB: "VCR Racing Team",
          posB: 25,
          ganador: "B",
        },
        {
          equipoA: "83 Campos Racing F1",
          posA: 17,
          equipoB: "72 Foxtrot GP",
          posB: 28,
          ganador: "A",
        },
        {
          equipoA: "13 Hispania Racing Team",
          posA: 27,
          equipoB: "Ferrari1",
          posB: 26,
          ganador: "B",
        },
        {
          equipoA: "Renfe Cercanías RT",
          posA: 21,
          equipoB: "Williams F1",
          posB: 6,
          ganador: "B",
        },
      ],
      resultados: null,
    },

    // ── JORNADA 2 · Estados Unidos ────────────────────────
    {
      numero: 2,
      circuito: "Estados Unidos",
      completada: true,
      enfrentamientos: [
        {
          equipoA: "77 Campos Racing F1",
          posA: 14,
          equipoB: "Ferrari1",
          posB: 24,
          ganador: "A",
        },
        {
          equipoA: "72 Foxtrot GP",
          posA: 17,
          equipoB: "Williams F1",
          posB: 10,
          ganador: "B",
        },
        {
          equipoA: "VCR Racing Team",
          posA: 28,
          equipoB: "Renfe Cercanías RT",
          posB: 27,
          ganador: "B",
        },
        {
          equipoA: "50 Rizia Royal Racing",
          posA: 1,
          equipoB: "13 Hispania Racing Team",
          posB: 25,
          ganador: "A",
        },
        {
          equipoA: "3 Zetta Racing",
          posA: 18,
          equipoB: "83 Campos Racing F1",
          posB: 20,
          ganador: "A",
        },
        {
          equipoA: "67 Renault Qatar Airways",
          posA: 6,
          equipoB: "Rayito Team",
          posB: 29,
          ganador: "A",
        },
        {
          equipoA: "99 Campos Racing F1",
          posA: 11,
          equipoB: "13 CRT Competition",
          posB: 9,
          ganador: "B",
        },
        {
          equipoA: "Red Bull Pinkustercia F1 Team",
          posA: 23,
          equipoB: "F. W. A.",
          posB: 22,
          ganador: "B",
        },
        {
          equipoA: "63 CRT Competition",
          posA: 3,
          equipoB: "Williams Racing",
          posB: 5,
          ganador: "A",
        },
        {
          equipoA: "23 Foxtrot GP",
          posA: 4,
          equipoB: "18 Zetta Racing",
          posB: 19,
          ganador: "A",
        },
        {
          equipoA: "49 Honda Repsol",
          posA: 2,
          equipoB: "Tortuga",
          posB: 7,
          ganador: "A",
        },
        {
          equipoA: "00 CRT Competition",
          posA: 13,
          equipoB: "Subaru F1 Team",
          posB: 8,
          ganador: "B",
        },
        {
          equipoA: "Ferrari",
          posA: 15,
          equipoB: "Zetta",
          posB: 26,
          ganador: "A",
        },
        {
          equipoA: "43 Campos Racing F1",
          posA: 21,
          equipoB: "18 Ferrari",
          posB: 30,
          ganador: "A",
        },
        {
          equipoA: "07 CRT Competition",
          posA: 12,
          equipoB: "36 CTC VCR FTSE",
          posB: 16,
          ganador: "A",
        },
      ],
      resultados: null,
    },

    // ── JORNADA 3 · Alemania ──────────────────────────────
    {
      numero: 3,
      circuito: "Alemania",
      completada: true,
      enfrentamientos: [
        {
          equipoA: "77 Campos Racing F1",
          posA: 1,
          equipoB: "Patria Italia",
          posB: 20,
          ganador: "A",
        },
        {
          equipoA: "Subaru F1 Team",
          posA: 16,
          equipoB: "Zetta",
          posB: 28,
          ganador: "A",
        },
        {
          equipoA: "Tortuga",
          posA: 7,
          equipoB: "18 Ferrari",
          posB: 17,
          ganador: "A",
        },
        {
          equipoA: "18 Zetta Racing",
          posA: 25,
          equipoB: "36 CTC VCR FTSE",
          posB: 29,
          ganador: "A",
        },
        {
          equipoA: "Williams Racing",
          posA: 13,
          equipoB: "07 CRT Competition",
          posB: 9,
          ganador: "B",
        },
        {
          equipoA: "F. W. A.",
          posA: 31,
          equipoB: "43 Campos Racing F1",
          posB: 19,
          ganador: "B",
        },
        {
          equipoA: "13 CRT Competition",
          posA: 11,
          equipoB: "Ferrari",
          posB: 14,
          ganador: "A",
        },
        {
          equipoA: "83 Campos Racing F1",
          posA: 18,
          equipoB: "00 CRT Competition",
          posB: 6,
          ganador: "B",
        },
        {
          equipoA: "13 Hispania Racing Team",
          posA: 21,
          equipoB: "49 Honda Repsol",
          posB: 10,
          ganador: "B",
        },
        {
          equipoA: "Renfe Cercanías RT",
          posA: 26,
          equipoB: "23 Foxtrot GP",
          posB: 4,
          ganador: "B",
        },
        {
          equipoA: "Williams F1",
          posA: 2,
          equipoB: "63 CRT Competition",
          posB: 12,
          ganador: "A",
        },
        {
          equipoA: "Ferrari1",
          posA: 23,
          equipoB: "Red Bull Pinkustercia F1 Team",
          posB: 27,
          ganador: "A",
        },
        {
          equipoA: "72 Foxtrot GP",
          posA: 15,
          equipoB: "99 Campos Racing F1",
          posB: 8,
          ganador: "B",
        },
        {
          equipoA: "VCR Racing Team",
          posA: 32,
          equipoB: "67 Renault Qatar Airways",
          posB: 3,
          ganador: "B",
        },
        {
          equipoA: "50 Rizia Royal Racing",
          posA: 5,
          equipoB: "3 Zetta Racing",
          posB: 24,
          ganador: "A",
        },
      ],
      resultados: null,
    },

    // ── JORNADA 4 · Países Bajos ──────────────────────────
    {
      numero: 4,
      circuito: "Países Bajos",
      completada: true,
      enfrentamientos: [
        {
          equipoA: "77 Campos Racing F1",
          posA: 2,
          equipoB: "Red Bull Pinkustercia F1 Team",
          posB: 27,
          ganador: "A",
        },
        {
          equipoA: "63 CRT Competition",
          posA: 9,
          equipoB: "99 Campos Racing F1",
          posB: 3,
          ganador: "B",
        },
        {
          equipoA: "23 Foxtrot GP",
          posA: 5,
          equipoB: "67 Renault Qatar Airways",
          posB: 16,
          ganador: "A",
        },
        {
          equipoA: "49 Honda Repsol",
          posA: 11,
          equipoB: "3 Zetta Racing",
          posB: 30,
          ganador: "A",
        },
        {
          equipoA: "00 CRT Competition",
          posA: 6,
          equipoB: "50 Rizia Royal Racing",
          posB: 7,
          ganador: "A",
        },
        {
          equipoA: "Ferrari",
          posA: 22,
          equipoB: "72 Foxtrot GP",
          posB: 12,
          ganador: "B",
        },
        {
          equipoA: "43 Campos Racing F1",
          posA: 18,
          equipoB: "Ferrari1",
          posB: 23,
          ganador: "A",
        },
        {
          equipoA: "07 CRT Competition",
          posA: 10,
          equipoB: "Williams F1",
          posB: 4,
          ganador: "B",
        },
        {
          equipoA: "36 CTC VCR FTSE",
          posA: 13,
          equipoB: "Renfe Cercanías RT",
          posB: 26,
          ganador: "A",
        },
        {
          equipoA: "18 Ferrari",
          posA: 17,
          equipoB: "13 Hispania Racing Team",
          posB: 24,
          ganador: "A",
        },
        {
          equipoA: "Zetta",
          posA: 29,
          equipoB: "83 Campos Racing F1",
          posB: 20,
          ganador: "B",
        },
        {
          equipoA: "Patria Italia",
          posA: 28,
          equipoB: "Rayito Team",
          posB: 21,
          ganador: "B",
        },
        {
          equipoA: "Subaru F1 Team",
          posA: 8,
          equipoB: "13 CRT Competition",
          posB: 25,
          ganador: "A",
        },
        {
          equipoA: "Tortuga",
          posA: 1,
          equipoB: "F. W. A.",
          posB: 32,
          ganador: "A",
        },
        {
          equipoA: "18 Zetta Racing",
          posA: 14,
          equipoB: "Williams Racing",
          posB: 15,
          ganador: "A",
        },
      ],
      resultados: null,
    },

    // ── JORNADA 5 · España ────────────────────────────────
    {
      numero: 5,
      circuito: "España",
      completada: true,
      enfrentamientos: [
        {
          equipoA: "77 Campos Racing F1",
          posA: 7,
          equipoB: "Rayito Team",
          posB: 20,
          ganador: "A",
        },
        {
          equipoA: "83 Campos Racing F1",
          posA: 14,
          equipoB: "13 CRT Competition",
          posB: 10,
          ganador: "B",
        },
        {
          equipoA: "13 Hispania Racing Team",
          posA: 17,
          equipoB: "F. W. A.",
          posB: 4,
          ganador: "B",
        },
        {
          equipoA: "Renfe Cercanías RT",
          posA: 26,
          equipoB: "Williams Racing",
          posB: 8,
          ganador: "B",
        },
        {
          equipoA: "Williams F1",
          posA: 13,
          equipoB: "18 Zetta Racing",
          posB: 23,
          ganador: "A",
        },
        {
          equipoA: "Ferrari1",
          posA: 24,
          equipoB: "Tortuga",
          posB: 22,
          ganador: "B",
        },
        {
          equipoA: "72 Foxtrot GP",
          posA: 5,
          equipoB: "Subaru F1 Team",
          posB: 25,
          ganador: "A",
        },
        {
          equipoA: "VCR Racing Team",
          posA: 32,
          equipoB: "Patria Italia",
          posB: 30,
          ganador: "B",
        },
        {
          equipoA: "50 Rizia Royal Racing",
          posA: 1,
          equipoB: "Zetta",
          posB: 31,
          ganador: "A",
        },
        {
          equipoA: "3 Zetta Racing",
          posA: 28,
          equipoB: "18 Ferrari",
          posB: 18,
          ganador: "B",
        },
        {
          equipoA: "67 Renault Qatar Airways",
          posA: 3,
          equipoB: "36 CTC VCR FTSE",
          posB: 27,
          ganador: "A",
        },
        {
          equipoA: "99 Campos Racing F1",
          posA: 6,
          equipoB: "07 CRT Competition",
          posB: 11,
          ganador: "A",
        },
        {
          equipoA: "Red Bull Pinkustercia F1 Team",
          posA: 16,
          equipoB: "43 Campos Racing F1",
          posB: 15,
          ganador: "B",
        },
        {
          equipoA: "63 CRT Competition",
          posA: 9,
          equipoB: "Ferrari",
          posB: 19,
          ganador: "A",
        },
        {
          equipoA: "49 Honda Repsol",
          posA: 2,
          equipoB: "00 CRT Competition",
          posB: 12,
          ganador: "A",
        },
      ],
      resultados: null,
    },

    // ── JORNADA 6 · Australia ─────────────────────────────
    // Enfrentamientos: pendiente de introducir manualmente
    // (ya no se usa igpleaguemanager, los resultados de carrera sí disponibles)
    {
      numero: 6,
      circuito: "Australia",
      completada: true,
      enfrentamientos: [
        {
          equipoA: "77 Campos Racing F1",
          posA: null,
          equipoB: "99 Campos Racing F1",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Red Bull Pinkustercia F1 Team",
          posA: null,
          equipoB: "67 Renault Qatar Airways",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "63 CRT Competition",
          posA: null,
          equipoB: "3 Zetta Racing",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "23 Foxtrot GP",
          posA: null,
          equipoB: "50 Rizia Royal Racing",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "49 Honda Repsol",
          posA: null,
          equipoB: "VCR Racing Team",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "00 CRT Competition",
          posA: null,
          equipoB: "72 Foxtrot GP",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Ferrari",
          posA: null,
          equipoB: "Williams F1",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "43 Campos Racing F1",
          posA: null,
          equipoB: "Renfe Cercanías RT",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "07 CRT Competition",
          posA: null,
          equipoB: "13 Hispania Racing Team",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "36 CTC VCR FTSE",
          posA: null,
          equipoB: "83 Campos Racing F1",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "18 Ferrari",
          posA: null,
          equipoB: "Rayito Team",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Zetta",
          posA: null,
          equipoB: "13 CRT Competition",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Patria Italia",
          posA: null,
          equipoB: "F. W. A.",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Subaru F1 Team",
          posA: null,
          equipoB: "Williams Racing",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Tortuga",
          posA: null,
          equipoB: "18 Zetta Racing",
          posB: null,
          ganador: null,
        },
      ],
      // Resultados individuales de la carrera (imagen J6)
      resultados: [
        {
          pos: 1,
          piloto: "F Orlando",
          equipo: "50 Rizia Royal Racing",
          finalizado: "0:46:11.169",
          mejorVuelta: "1:25.606",
          velMax: 219.05,
          boxes: 2,
          pts: 50,
        },
        {
          pos: 2,
          piloto: "D Antsyforov",
          equipo: "Subaru F1 Team",
          finalizado: "+0:00.108",
          mejorVuelta: "1:25.623",
          velMax: 219.05,
          boxes: 2,
          pts: 40,
        },
        {
          pos: 3,
          piloto: "I Molinelli",
          equipo: "49 Honda Repsol",
          finalizado: "+0:00.117",
          mejorVuelta: "1:25.307",
          velMax: 219.05,
          boxes: 2,
          pts: 35,
        },
        {
          pos: 4,
          piloto: "D Moss",
          equipo: "77 Campos Racing F1",
          finalizado: "+0:00.186",
          mejorVuelta: "1:25.218",
          velMax: 219.05,
          boxes: 2,
          pts: 33,
        },
        {
          pos: 5,
          piloto: "R Manu",
          equipo: "Williams Racing",
          finalizado: "+0:01.106",
          mejorVuelta: "1:25.936",
          velMax: 219.05,
          boxes: 2,
          pts: 30,
        },
        {
          pos: 6,
          piloto: "R Mansell",
          equipo: "Tortuga",
          finalizado: "+0:01.462",
          mejorVuelta: "1:26.025",
          velMax: 219.05,
          boxes: 2,
          pts: 26,
        },
        {
          pos: 7,
          piloto: "R Walker",
          equipo: "83 Campos Racing F1",
          finalizado: "+0:01.939",
          mejorVuelta: "1:27.450",
          velMax: 219.05,
          boxes: 2,
          pts: 24,
        },
        {
          pos: 8,
          piloto: "S Solano",
          equipo: "13 CRT Competition",
          finalizado: "+0:02.552",
          mejorVuelta: "1:27.715",
          velMax: 219.05,
          boxes: 2,
          pts: 22,
        },
        {
          pos: 9,
          piloto: "F Giacomina",
          equipo: "23 Foxtrot GP",
          finalizado: "+0:02.770",
          mejorVuelta: "1:27.237",
          velMax: 219.05,
          boxes: 2,
          pts: 20,
        },
        {
          pos: 10,
          piloto: "A Greniuk",
          equipo: "63 CRT Competition",
          finalizado: "+0:03.260",
          mejorVuelta: "1:26.664",
          velMax: 219.05,
          boxes: 2,
          pts: 18,
        },
        {
          pos: 11,
          piloto: "F AzJe",
          equipo: "Ferrari",
          finalizado: "+0:03.434",
          mejorVuelta: "1:28.486",
          velMax: 219.05,
          boxes: 2,
          pts: 12,
        },
        {
          pos: 12,
          piloto: "C Ezpeleta",
          equipo: "99 Campos Racing F1",
          finalizado: "+0:04.625",
          mejorVuelta: "1:27.998",
          velMax: 219.05,
          boxes: 2,
          pts: 10,
        },
        {
          pos: 13,
          piloto: "S Seferoğlu",
          equipo: "Williams F1",
          finalizado: "+0:04.627",
          mejorVuelta: "1:28.652",
          velMax: 219.05,
          boxes: 2,
          pts: 9,
        },
        {
          pos: 14,
          piloto: "A Es Grande",
          equipo: "F. W. A.",
          finalizado: "+0:05.099",
          mejorVuelta: "1:28.964",
          velMax: 219.05,
          boxes: 2,
          pts: 8,
        },
        {
          pos: 15,
          piloto: "L Neumann",
          equipo: "67 Renault Qatar Airways",
          finalizado: "+0:07.241",
          mejorVuelta: "1:31.496",
          velMax: 219.05,
          boxes: 2,
          pts: 7,
        },
        {
          pos: 16,
          piloto: "M Medina",
          equipo: "43 Campos Racing F1",
          finalizado: "+0:07.895",
          mejorVuelta: "1:29.726",
          velMax: 219.05,
          boxes: 2,
          pts: 5,
        },
        {
          pos: 17,
          piloto: "J Hunt",
          equipo: "00 CRT Competition",
          finalizado: "+0:09.836",
          mejorVuelta: "1:34.155",
          velMax: 219.05,
          boxes: 2,
          pts: 4,
        },
        {
          pos: 18,
          piloto: "G Flores",
          equipo: "18 Ferrari",
          finalizado: "+0:09.947",
          mejorVuelta: "1:33.924",
          velMax: 219.05,
          boxes: 2,
          pts: 3,
        },
        {
          pos: 19,
          piloto: "O White",
          equipo: "Patria Italia",
          finalizado: "+0:10.306",
          mejorVuelta: "1:32.856",
          velMax: 219.05,
          boxes: 2,
          pts: 2,
        },
        {
          pos: 20,
          piloto: "M Palmer",
          equipo: "Red Bull Pinkustercia F1 Team",
          finalizado: "+0:10.321",
          mejorVuelta: "1:31.359",
          velMax: 219.05,
          boxes: 2,
          pts: 1,
        },
        {
          pos: 21,
          piloto: "L Ferreira",
          equipo: "07 CRT Competition",
          finalizado: "+0:10.949",
          mejorVuelta: "1:33.910",
          velMax: 219.05,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 22,
          piloto: "I Ceballos",
          equipo: "18 Zetta Racing",
          finalizado: "+0:11.186",
          mejorVuelta: "1:33.625",
          velMax: 219.05,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 23,
          piloto: "M Erecto",
          equipo: "3 Zetta Racing",
          finalizado: "+0:11.240",
          mejorVuelta: "1:33.744",
          velMax: 219.05,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 24,
          piloto: "D Thomas",
          equipo: "Ferrari1",
          finalizado: "+0:11.554",
          mejorVuelta: "1:31.900",
          velMax: 219.05,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 25,
          piloto: "I Menarquez",
          equipo: "72 Foxtrot GP",
          finalizado: "+0:12.009",
          mejorVuelta: "1:33.585",
          velMax: 219.05,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 26,
          piloto: "R Thompson",
          equipo: "Rayito Team",
          finalizado: "+0:13.833",
          mejorVuelta: "1:34.172",
          velMax: 219.05,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 27,
          piloto: "L Halcón",
          equipo: "13 Hispania Racing Team",
          finalizado: "+0:28.616",
          mejorVuelta: "1:33.663",
          velMax: 218.13,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 28,
          piloto: "J Villeneuve",
          equipo: "Zetta",
          finalizado: "+0:37.532",
          mejorVuelta: "1:33.652",
          velMax: 219.05,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 29,
          piloto: "J Calvo",
          equipo: "VCR Racing Team",
          finalizado: "+0:41.213",
          mejorVuelta: "1:32.582",
          velMax: 209.91,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 30,
          piloto: "L Robinson",
          equipo: "36 CTC VCR FTSE",
          finalizado: "+0:50.589",
          mejorVuelta: "1:35.589",
          velMax: 216.84,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 31,
          piloto: "F Martinez",
          equipo: "Renfe Cercanías RT",
          finalizado: "+2:03.495",
          mejorVuelta: "1:35.669",
          velMax: 219.05,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 32,
          piloto: "L Sexo Fernández",
          equipo: "Castrol F1 Team",
          finalizado: "+1 vuelta",
          mejorVuelta: "1:38.004",
          velMax: 207.33,
          boxes: 2,
          pts: 0,
        },
      ],
    },

    // ── JORNADA 7 · Baréin ────────────────────────────────
    {
      numero: 7,
      circuito: "Baréin",
      completada: true,
      enfrentamientos: [
        {
          equipoA: "77 Campos Racing F1",
          posA: 10,
          equipoB: "Zetta",
          posB: 28,
          ganador: "A",
        },
        {
          equipoA: "Patria Italia",
          posA: 31,
          equipoB: "18 Ferrari",
          posB: 14,
          ganador: "B",
        },
        {
          equipoA: "Subaru F1 Team",
          posA: 2,
          equipoB: "36 CTC VCR FTSE",
          posB: 26,
          ganador: "A",
        },
        {
          equipoA: "Tortuga",
          posA: 1,
          equipoB: "07 CRT Competition",
          posB: 11,
          ganador: "A",
        },
        {
          equipoA: "18 Zetta Racing",
          posA: 32,
          equipoB: "43 Campos Racing F1",
          posB: 23,
          ganador: "B",
        },
        {
          equipoA: "Williams Racing",
          posA: 6,
          equipoB: "Ferrari",
          posB: 24,
          ganador: "A",
        },
        {
          equipoA: "13 CRT Competition",
          posA: 16,
          equipoB: "00 CRT Competition",
          posB: 13,
          ganador: "B",
        },
        {
          equipoA: "Rayito Team",
          posA: 25,
          equipoB: "49 Honda Repsol",
          posB: 5,
          ganador: "B",
        },
        {
          equipoA: "83 Campos Racing F1",
          posA: 18,
          equipoB: "23 Foxtrot GP",
          posB: 20,
          ganador: "A",
        },
        {
          equipoA: "13 Hispania Racing Team",
          posA: 27,
          equipoB: "63 CRT Competition",
          posB: 8,
          ganador: "B",
        },
        {
          equipoA: "Renfe Cercanías RT",
          posA: 22,
          equipoB: "Red Bull Pinkustercia F1 Team",
          posB: 15,
          ganador: "B",
        },
        {
          equipoA: "Williams F1",
          posA: 12,
          equipoB: "99 Campos Racing F1",
          posB: 7,
          ganador: "B",
        },
        {
          equipoA: "Ferrari1",
          posA: 21,
          equipoB: "67 Renault Qatar Airways",
          posB: 9,
          ganador: "B",
        },
        {
          equipoA: "72 Foxtrot GP",
          posA: 4,
          equipoB: "3 Zetta Racing",
          posB: 19,
          ganador: "A",
        },
        {
          equipoA: "VCR Racing Team",
          posA: 30,
          equipoB: "50 Rizia Royal Racing",
          posB: 3,
          ganador: "B",
        },
      ],
      // Resultados individuales de la carrera (imagen J7 — Baréin)
      resultados: [
        {
          pos: 1,
          piloto: "R Mansell",
          equipo: "Tortuga",
          finalizado: "0:48:58.591",
          mejorVuelta: "1:29.682",
          velMax: 192.14,
          boxes: 2,
          pts: 50,
        },
        {
          pos: 2,
          piloto: "D Antsyforov",
          equipo: "Subaru F1 Team",
          finalizado: "+0:00.456",
          mejorVuelta: "1:28.908",
          velMax: 192.14,
          boxes: 2,
          pts: 40,
        },
        {
          pos: 3,
          piloto: "F Orlando",
          equipo: "50 Rizia Royal Racing",
          finalizado: "+0:00.616",
          mejorVuelta: "1:29.721",
          velMax: 192.14,
          boxes: 2,
          pts: 35,
        },
        {
          pos: 4,
          piloto: "I Menarguez",
          equipo: "72 Foxtrot GP",
          finalizado: "+0:01.505",
          mejorVuelta: "1:29.711",
          velMax: 192.14,
          boxes: 2,
          pts: 32,
        },
        {
          pos: 5,
          piloto: "I Molinelli",
          equipo: "49 Honda Repsol",
          finalizado: "+0:01.692",
          mejorVuelta: "1:27.830",
          velMax: 192.14,
          boxes: 2,
          pts: 30,
        },
        {
          pos: 6,
          piloto: "R Manu",
          equipo: "Williams Racing",
          finalizado: "+0:01.803",
          mejorVuelta: "1:31.792",
          velMax: 192.14,
          boxes: 2,
          pts: 26,
        },
        {
          pos: 7,
          piloto: "C Ezpeleta",
          equipo: "99 Campos Racing F1",
          finalizado: "+0:02.585",
          mejorVuelta: "1:30.543",
          velMax: 192.14,
          boxes: 2,
          pts: 24,
        },
        {
          pos: 8,
          piloto: "A Greniuk",
          equipo: "63 CRT Competition",
          finalizado: "+0:02.629",
          mejorVuelta: "1:27.493",
          velMax: 192.14,
          boxes: 2,
          pts: 23,
        },
        {
          pos: 9,
          piloto: "L Neumann",
          equipo: "67 Renault Qatar Airways",
          finalizado: "+0:04.568",
          mejorVuelta: "1:29.046",
          velMax: 192.14,
          boxes: 2,
          pts: 20,
        },
        {
          pos: 10,
          piloto: "D Moss",
          equipo: "77 Campos Racing F1",
          finalizado: "+0:04.646",
          mejorVuelta: "1:29.680",
          velMax: 192.14,
          boxes: 2,
          pts: 18,
        },
        {
          pos: 11,
          piloto: "L Ferreira",
          equipo: "07 CRT Competition",
          finalizado: "+0:08.523",
          mejorVuelta: "1:31.400",
          velMax: 192.14,
          boxes: 2,
          pts: 12,
        },
        {
          pos: 12,
          piloto: "S Seferoğlu",
          equipo: "Williams F1",
          finalizado: "+0:11.372",
          mejorVuelta: "1:31.020",
          velMax: 192.14,
          boxes: 2,
          pts: 10,
        },
        {
          pos: 13,
          piloto: "J Hunt",
          equipo: "00 CRT Competition",
          finalizado: "+0:11.815",
          mejorVuelta: "1:35.200",
          velMax: 192.14,
          boxes: 2,
          pts: 9,
        },
        {
          pos: 14,
          piloto: "G Flores",
          equipo: "18 Ferrari",
          finalizado: "+0:13.364",
          mejorVuelta: "1:34.046",
          velMax: 192.14,
          boxes: 2,
          pts: 8,
        },
        {
          pos: 15,
          piloto: "M Palmer",
          equipo: "Red Bull Pinkustercia F1 Team",
          finalizado: "+0:13.932",
          mejorVuelta: "1:35.942",
          velMax: 192.14,
          boxes: 2,
          pts: 7,
        },
        {
          pos: 16,
          piloto: "S Solano",
          equipo: "13 CRT Competition",
          finalizado: "+0:14.701",
          mejorVuelta: "1:33.889",
          velMax: 192.14,
          boxes: 2,
          pts: 5,
        },
        {
          pos: 17,
          piloto: "A Es Grande",
          equipo: "F. W. A.",
          finalizado: "+0:15.549",
          mejorVuelta: "1:34.538",
          velMax: 192.14,
          boxes: 2,
          pts: 4,
        },
        {
          pos: 18,
          piloto: "R Walker",
          equipo: "83 Campos Racing F1",
          finalizado: "+0:17.945",
          mejorVuelta: "1:36.634",
          velMax: 192.14,
          boxes: 2,
          pts: 3,
        },
        {
          pos: 19,
          piloto: "M Erecto",
          equipo: "3 Zetta Racing",
          finalizado: "+0:18.332",
          mejorVuelta: "1:36.548",
          velMax: 192.14,
          boxes: 2,
          pts: 2,
        },
        {
          pos: 20,
          piloto: "F Giacomina",
          equipo: "23 Foxtrot GP",
          finalizado: "+0:22.340",
          mejorVuelta: "1:34.433",
          velMax: 192.14,
          boxes: 2,
          pts: 1,
        },
        {
          pos: 21,
          piloto: "D Thomas",
          equipo: "Ferrari1",
          finalizado: "+0:29.210",
          mejorVuelta: "1:37.014",
          velMax: 192.14,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 22,
          piloto: "F Martinez",
          equipo: "Renfe Cercanías RT",
          finalizado: "+0:29.293",
          mejorVuelta: "1:35.345",
          velMax: 192.14,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 23,
          piloto: "M Medina",
          equipo: "43 Campos Racing F1",
          finalizado: "+0:31.907",
          mejorVuelta: "1:29.816",
          velMax: 192.14,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 24,
          piloto: "F AzJe",
          equipo: "Ferrari",
          finalizado: "+0:32.018",
          mejorVuelta: "1:37.849",
          velMax: 192.14,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 25,
          piloto: "F Panis",
          equipo: "Rayito Team",
          finalizado: "+0:35.569",
          mejorVuelta: "1:37.006",
          velMax: 192.14,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 26,
          piloto: "L Robinson",
          equipo: "36 CTC VCR FTSE",
          finalizado: "+0:36.881",
          mejorVuelta: "1:33.358",
          velMax: 192.14,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 27,
          piloto: "L Halcón",
          equipo: "13 Hispania Racing Team",
          finalizado: "+0:36.985",
          mejorVuelta: "1:35.846",
          velMax: 192.14,
          boxes: 3,
          pts: 0,
        },
        {
          pos: 28,
          piloto: "J Villeneuve",
          equipo: "Zetta",
          finalizado: "+1:00.164",
          mejorVuelta: "1:38.654",
          velMax: 192.14,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 29,
          piloto: "L Sexo Fernández",
          equipo: "Castrol F1 Team",
          finalizado: "+1 vuelta",
          mejorVuelta: "1:38.723",
          velMax: 192.14,
          boxes: 3,
          pts: 0,
        },
        {
          pos: 30,
          piloto: "J Calvo",
          equipo: "VCR Racing Team",
          finalizado: "Combustible",
          mejorVuelta: "1:37.337",
          velMax: 192.14,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 31,
          piloto: "O White",
          equipo: "Patria italia",
          finalizado: "Combustible",
          mejorVuelta: "1:36.721",
          velMax: 192.14,
          boxes: 2,
          pts: 0,
        },
        {
          pos: 32,
          piloto: "I Ceballos",
          equipo: "18 Zetta Racing",
          finalizado: "Combustible",
          mejorVuelta: "1:37.228",
          velMax: 192.14,
          boxes: 2,
          pts: 0,
        },
      ],
    },

    // ── JORNADA 8 · Rusia ─────────────────────────────────
    {
      numero: 8,
      circuito: "Rusia",
      completada: false,
      enfrentamientos: [
        {
          equipoA: "77 Campos Racing F1",
          posA: null,
          equipoB: "83 Campos Racing F1",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "13 Hispania Racing Team",
          posA: null,
          equipoB: "Rayito Team",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Renfe Cercanías RT",
          posA: null,
          equipoB: "13 CRT Competition",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Williams F1",
          posA: null,
          equipoB: "F. W. A.",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Ferrari1",
          posA: null,
          equipoB: "Williams Racing",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "72 Foxtrot GP",
          posA: null,
          equipoB: "18 Zetta Racing",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "VCR Racing Team",
          posA: null,
          equipoB: "Tortuga",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "50 Rizia Royal Racing",
          posA: null,
          equipoB: "Subaru F1 Team",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "3 Zetta Racing",
          posA: null,
          equipoB: "Patria Italia",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "67 Renault Qatar Airways",
          posA: null,
          equipoB: "Zetta",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "99 Campos Racing F1",
          posA: null,
          equipoB: "18 Ferrari",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Red Bull Pinkustercia F1 Team",
          posA: null,
          equipoB: "36 CTC VCR FTSE",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "63 CRT Competition",
          posA: null,
          equipoB: "07 CRT Competition",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "23 Foxtrot GP",
          posA: null,
          equipoB: "43 Campos Racing F1",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "49 Honda Repsol",
          posA: null,
          equipoB: "Ferrari",
          posB: null,
          ganador: null,
        },
      ],
      resultados: null,
    },

    // ── JORNADA 9 · Japón ─────────────────────────────────
    {
      numero: 9,
      circuito: "Japón",
      completada: false,
      enfrentamientos: [
        {
          equipoA: "77 Campos Racing F1",
          posA: null,
          equipoB: "07 CRT Competition",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "36 CTC VCR FTSE",
          posA: null,
          equipoB: "43 Campos Racing F1",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "18 Ferrari",
          posA: null,
          equipoB: "Ferrari",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Patria Italia",
          posA: null,
          equipoB: "00 CRT Competition",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Subaru F1 Team",
          posA: null,
          equipoB: "49 Honda Repsol",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Tortuga",
          posA: null,
          equipoB: "23 Foxtrot GP",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "18 Zetta Racing",
          posA: null,
          equipoB: "63 CRT Competition",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Williams Racing",
          posA: null,
          equipoB: "Red Bull Pinkustercia F1 Team",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "F. W. A.",
          posA: null,
          equipoB: "99 Campos Racing F1",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "13 CRT Competition",
          posA: null,
          equipoB: "67 Renault Qatar Airways",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Rayito Team",
          posA: null,
          equipoB: "3 Zetta Racing",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "83 Campos Racing F1",
          posA: null,
          equipoB: "50 Rizia Royal Racing",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "13 Hispania Racing Team",
          posA: null,
          equipoB: "VCR Racing Team",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Renfe Cercanías RT",
          posA: null,
          equipoB: "72 Foxtrot GP",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Williams F1",
          posA: null,
          equipoB: "Ferrari1",
          posB: null,
          ganador: null,
        },
      ],
      resultados: null,
    },

    // ── JORNADA 10 · Singapur ─────────────────────────────
    {
      numero: 10,
      circuito: "Singapur",
      completada: false,
      enfrentamientos: [
        {
          equipoA: "77 Campos Racing F1",
          posA: null,
          equipoB: "36 CTC VCR FTSE",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "18 Ferrari",
          posA: null,
          equipoB: "07 CRT Competition",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Zetta",
          posA: null,
          equipoB: "43 Campos Racing F1",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Patria Italia",
          posA: null,
          equipoB: "Ferrari",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Tortuga",
          posA: null,
          equipoB: "00 CRT Competition",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "18 Zetta Racing",
          posA: null,
          equipoB: "49 Honda Repsol",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Williams Racing",
          posA: null,
          equipoB: "23 Foxtrot GP",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "F. W. A.",
          posA: null,
          equipoB: "63 CRT Competition",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "13 CRT Competition",
          posA: null,
          equipoB: "Red Bull Pinkustercia F1 Team",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Rayito Team",
          posA: null,
          equipoB: "99 Campos Racing F1",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "83 Campos Racing F1",
          posA: null,
          equipoB: "67 Renault Qatar Airways",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "13 Hispania Racing Team",
          posA: null,
          equipoB: "3 Zetta Racing",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Renfe Cercanías RT",
          posA: null,
          equipoB: "50 Rizia Royal Racing",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Williams F1",
          posA: null,
          equipoB: "VCR Racing Team",
          posB: null,
          ganador: null,
        },
        {
          equipoA: "Ferrari1",
          posA: null,
          equipoB: "72 Foxtrot GP",
          posB: null,
          ganador: null,
        },
      ],
      resultados: null,
    },
  ],

  // ── ELIMINATORIAS ─────────────────────────────────────────
  eliminatorias: {
    octavos: [],
    cuartos: [],
    semis: [],
    final: {
      id: "fin-1",
      p1: "TBD",
      s1: "G",
      p2: "TBD",
      s2: "G",
      ganador: null,
      posG: null,
      posL: null,
    },
  },

  // ── SOCIAL / REDES ────────────────────────────────────────
  redes: [
    {
      label: "TikTok",
      href: "https://www.tiktok.com/@calvo.plan?_r=1&_t=ZN-93aEsFGNWVi",
    },
    { label: "Twitch", href: "https://www.twitch.tv/sergiote_g20" },
    { label: "Twitch Alt", href: "https://www.twitch.tv/prodigss" },
    {
      label: "YouTube",
      href: "https://youtube.com/@spanishracingseries?si=9LkAzkI-EK1h5c3W",
    },
    { label: "Discord", href: "https://discord.gg/anDChwwQA" },
    {
      label: "Instagram",
      href: "https://www.instagram.com/spanishracingseries_?igsh=MXZiMnczNXBraDJobw==",
    },
    {
      label: "WhatsApp",
      href: "https://chat.whatsapp.com/KVf4sll1iDi8RmqroMjWDa",
    },
  ],
};
